```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  pod:
    # FIXME: use the right IP
    server: 07e644a3a8-rme57.cn-hangzhou.nas.aliyuncs.com
    path: "/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
```


```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 2                                   # 镜像副本数量
  template:
    metadata:
      labels:                                   # 容器的标签 可和service关联
        app: nginx
    spec:
      containers:
        - name: nginx                           # 容器名
          image: nginx:1.8                      # 容器镜像
          volumeMounts:
          # name must match the volume name below
            - name: pod
              mountPath: "/pod"
      volumes:
      - name: pod
        persistentVolumeClaim:
          claimName: pod