version: '2'
services:
  drone-server:
    image: drone/drone:0.8.2
    container_name: drone-server
    ports:
      - 80:8000
      - 9000:9000
    volumes:
      - /etc/drone:/var/lib/drone/
    restart: always
    environment:
      # 是否允许注册，false 后只有在 DRONE_ADMIN 变量中指定的账户才能登录
      - DRONE_OPEN=true
      # admin
      - DRONE_ADMIN=drone,mritd
      # Drone可公开访问的地址,Drone的安装服务器, 不需要端口
      - DRONE_HOST=http://127.0.0.1/
      # 配置 Git 仓库，只能同时使用一种仓库
      # Gitlab 仓库需要配置上问申请到的 client id 和 client secret
      - DRONE_GITLAB=true
      - DRONE_GITLAB_URL=http://code.keke.com
      - DRONE_GITLAB_CLIENT=11jfdsdkjfhcdedd16b
      - DRONE_GITLAB_SECRET=2jjkjsklankdd2ad
      # Drone Server 和 Agent 的通信密钥,随意填写
      - DRONE_SECRET={DRONE_SECRET}
  drone-agent:
    image: drone/agent:0.8.2
    container_name: drone-agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # 配置 SERVER 地址
      - DRONE_SERVER=drone-server:9000
      # 配置与 SERVER 通信的密钥，需要与 Server 配置的保持一致
      - DRONE_SECRET={DRONE_SECRET}