gitlab应用部署yaml:

```bash
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce-service
  labels:
    app: gitlab-ce-service
spec:
  ports:
    - name: gitlab-ce
      port: 80                     # 通过service来访问的端口
      targetPort: 80               # 对应容器的端口
      nodePort: 30000
  selector:
    app: gitlab-ce                 # service负载的容器需要有同样的labels
  type: NodePort                   # 开发端口的类型
---
apiVersion: extensions/v1beta1     # K8S对应的API版本
kind: Deployment                   # 对应的类型
metadata:
  name: gitlab-deployment
  labels:
    app: gitlab-deployment
spec:
  replicas: 1                                   # 镜像副本数量
  template:
    metadata:
      labels:
        app: gitlab-ce                 # 容器的标签 可和service关联
    spec:
      containers:
        - name: gitlab-ce               # 容器名
          image: twang2218/gitlab-ce-zh:10.6.2 #镜像
          imagePullPolicy: Always
```
