---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-myapp
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: myapp.sun.com
      http:
        paths:
          - path:
            backend:
              serviceName: myapp
              servicePort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-gitlab
  labels:
     app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
